const actionsType = {
    TOGGLE_INPUT_NEW_TASK: "TOGGLE_INPUT_NEW_TASK",
    CREATE_NEW_TASK: "CREATE_NEW_TASK",
    OPEN_MODAL_TASK: "OPEN_MODAL_TASK",
    CLOSE_MODAL: "CLOSE_MODAL",
    UPDATE_TASK_POSITION: "UPDATE_TASK_POSITION"
}

export default actionsType;