const actionsType = {
    TOGGLE_INPUT_NEW_TASK: "TOGGLE_INPUT_NEW_TASK",
    CREATE_NEW_TASK: "CREATE_NEW_TASK",
    OPEN_MODAL_TASK: "OPEN_MODAL_TASK",
    CLOSE_MODAL: "CLOSE_MODAL",
    UPDATE_TASK_COLUMN: "UPDATE_TASK_COLUMN",
    UPDATE_TASK_POSITION: "UPDATE_TASK_POSITION",
    LOAD_COLUMNS_SUCCESS : 'LOAD_COLUMNS_SUCCESS',
    LOADING_COLUMNS : 'LOADING_COLUMNS'
}

export default actionsType;  